### ISSUE TITLE
Option to costumze text align

### ISSUE THREAD

**Issue by ghost** [wpexplorer/wpex-pineapple#1]
Hi!

I like very much your theme, but there are a couple of details I miss. 

It is possible to add a customize option to change the alignment of the text? I prefer it aligned to the left. 

I can put a custom CSS without problems, but I think it's a feature that will be welcomed. 

Thanks!

**Comment by wpexplorer** [comment]
@aperalesf  - I've finally updated the theme and converted it to a block theme which you can get here: https://wordpress.org/themes/pineapple-wpex/ - Enjoy!
